# Cancel
name: cancel_previous
on: [push]
jobs:
  cancel:
    name: "Cancel Previous Runs"
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: styfle/cancel-workflow-action@0.9.1
        with:
          workflow_id: >-
            all_plugins.yaml,
            wifi_iot.yaml,
            wifi_scan.yaml,
            wifi_passpoint.yaml
          all_but_latest: true